# docker-compose.yml
version: '3.8'

services:
  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_MINIO_URL=http://localhost:9000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - portfolio-network

  # Backend (Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - minio
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
    networks:
      - portfolio-network
    restart: unless-stopped

  # MinIO (File Storage)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_PUBLIC_URL=http://localhost:9000
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - portfolio-network
    restart: unless-stopped

  # Optional: Database backup service
  backup:
    image: alpine:latest
    volumes:
      - ./backup:/backup
      - ./backend/data:/data
    command: |
      sh -c "
        while true; do
          tar -czf /backup/db_backup_$(date +%Y%m%d_%H%M%S).tar.gz -C /data .
          find /backup -name '*.tar.gz' -mtime +7 -delete
          sleep 86400
        done
      "
    depends_on:
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  minio_data:
  backend_data: