# docker-compose.yml - ИСПРАВЛЕННАЯ ВЕРСИЯ для nginx
version: '3.8'

services:
  # Frontend (React) - порт 3100
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3100:3100"  # nginx проксирует на этот порт
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://kartofan.online/api
      - REACT_APP_MINIO_URL=https://kartofan.online/media
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - portfolio-network
    restart: unless-stopped

  # Backend (Express) - порт 8100
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8100:8100"  # nginx проксирует /api/* на этот порт
    depends_on:
      - minio
    environment:
      - NODE_ENV=production
      - PORT=8100
      - CORS_ORIGIN=https://kartofan.online
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-2025}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      # ✅ ИСПРАВЛЕНИЕ: Используем имя сервиса Docker для MinIO
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-prodportfolioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-prod-portfolio-secret-key-2025}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-portfolio-files}
      - MINIO_PUBLIC_URL=https://kartofan.online/media
    volumes:
      - ./backend/data:/app/data
    networks:
      - portfolio-network
    restart: unless-stopped
    # ✅ Ждем запуска MinIO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # MinIO (File Storage) - порт 9000
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"   # nginx проксирует /media/* на этот порт
      - "9001:9001"   # админка MinIO
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-prodportfolioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-prod-portfolio-secret-key-2025}
      # ✅ Дополнительные настройки для nginx
      - MINIO_SERVER_URL=https://kartofan.online/media
      - MINIO_BROWSER_REDIRECT_URL=https://kartofan.online:9001
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001" --address ":9000"
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  portfolio-network:
    driver: bridge

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local