# docker-compose.yml - ИСПРАВЛЕННАЯ ВЕРСИЯ с CORS
version: '3.8'

services:
  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8100
      - REACT_APP_MINIO_URL=http://localhost:9000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - portfolio-network

  # Backend (Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - minio
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_PUBLIC_URL=http://localhost:9000  # ✅ НОВАЯ ПЕРЕМЕННАЯ
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
    networks:
      - portfolio-network
    restart: unless-stopped

  # MinIO (File Storage) - ✅ ИСПРАВЛЕННАЯ ВЕРСИЯ с CORS
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      # ✅ ДОБАВЛЯЕМ CORS НАСТРОЙКИ
      - MINIO_API_CORS_ALLOW_ORIGIN=*
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      # ✅ ДОПОЛНИТЕЛЬНЫЕ НАСТРОЙКИ ДЛЯ CORS
      - MINIO_API_SELECT_PARQUET=on
      - MINIO_API_REQUESTS_MAX=1000
      - MINIO_API_REQUESTS_DEADLINE=10s
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001" --address ":9000"
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Optional: Database backup service
  backup:
    image: alpine:latest
    volumes:
      - ./backup:/backup
      - ./backend/data:/data
    command: |
      sh -c "
        while true; do
          tar -czf /backup/db_backup_$(date +%Y%m%d_%H%M%S).tar.gz -C /data .
          find /backup -name '*.tar.gz' -mtime +7 -delete
          sleep 86400
        done
      "
    depends_on:
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  minio_data:
  backend_data: