# docker-compose.yml - ИСПРАВЛЕННАЯ ВЕРСИЯ для nginx с фиксом MinIO
version: '3.8'

services:
  # Frontend (React) - порт 3100
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://kartofan.online/api
      - REACT_APP_MINIO_URL=https://kartofan.online/media
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - portfolio-network
    restart: unless-stopped

  # Backend (Express) - порт 8100
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      minio:
        condition: service_healthy  # ✅ Ждем здоровое состояние MinIO
    environment:
      - NODE_ENV=production
      - PORT=8100
      - CORS_ORIGIN=https://kartofan.online
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-2025}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      # ✅ ИСПРАВЛЕНИЕ: Используем имя сервиса Docker для MinIO
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-prodportfolioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-prod-portfolio-secret-key-2025}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-portfolio-files}
      - MINIO_PUBLIC_URL=https://kartofan.online/media
    volumes:
      - ./backend/data:/app/data
    networks:
      - portfolio-network
    restart: unless-stopped
    # ✅ Обновленный healthcheck с большими таймаутами
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/api/health"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 120s  # Увеличиваем время запуска

  # MinIO (File Storage) - порт 9000
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-prodportfolioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-prod-portfolio-secret-key-2025}
      # ✅ ИСПРАВЛЕНИЕ: Убираем проблемные URL настройки
      - MINIO_BROWSER_REDIRECT_URL=https://kartofan.online:9001
      # ✅ ДОБАВЛЯЕМ настройки для корректной работы
      - MINIO_REGION_NAME=us-east-1
      - MINIO_DOMAIN=kartofan.online
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    # ✅ ИСПРАВЛЕНИЕ: Обновленная команда запуска
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - portfolio-network
    restart: unless-stopped
    # ✅ Улучшенный healthcheck для MinIO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  portfolio-network:
    driver: bridge
    # ✅ ДОБАВЛЯЕМ настройки сети
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local